#!/usr/bin/env bash
set -euo pipefail

TF_DIR="${TF_DIR:-terraform}"
AWS_REGION="${AWS_REGION:-us-east-1}"
BACKEND_BUCKET="${BACKEND_BUCKET:-tfstate-cif0ip}"
LOCK_TABLE="${LOCK_TABLE:-tf-locks}"
BACKEND_KEY="${BACKEND_KEY:-cmonthe2/sns-repo/terraform.tfstate}"

need(){ command -v "$1" >/dev/null 2>&1 || { echo "❌ Missing: $1"; exit 1; }; }
need aws; need jq; need terraform

mkdir -p "$TF_DIR"

# ---- Ensure provider + backend ----
if [ ! -f "$TF_DIR/providers.tf" ]; then
  cat > "$TF_DIR/providers.tf" <<EOF
terraform {
  required_version = ">= 1.8.0"
  backend "s3" {}
  required_providers {
    aws = { source = "hashicorp/aws", version = ">= 5.0" }
  }
}

provider "aws" {
  region = "${AWS_REGION}"
}
EOF
fi

if [ ! -f "$TF_DIR/variables.tf" ]; then
  cat > "$TF_DIR/variables.tf" <<EOF
variable "region" {
  description = "AWS region"
  type        = string
  default     = "${AWS_REGION}"
}
EOF
fi

MAIN="$TF_DIR/sns.tf"
echo "########################################################" > "$MAIN"
echo "# Generated by import_sns.sh" >> "$MAIN"
echo "########################################################" >> "$MAIN"
echo >> "$MAIN"

# 🔑 Always init backend
(
  cd "$TF_DIR" && terraform init -reconfigure \
    -backend-config="bucket=${BACKEND_BUCKET}" \
    -backend-config="region=${AWS_REGION}" \
    -backend-config="dynamodb_table=${LOCK_TABLE}" \
    -backend-config="encrypt=true" \
    -backend-config="key=${BACKEND_KEY}"
)

# Helpers
tf_id(){ echo "${1//[^a-zA-Z0-9_]/_}"; }
safe_import() {
  local addr="$1" id="$2"
  if terraform state list | grep -q "^${addr}$"; then
    echo "⚠️  Already in state: $addr"
  else
    echo "➡️  Importing $addr ($id)"
    terraform import -input=false "$addr" "$id" || true
  fi
}

# ---- Topics ----
echo "⏳ Listing SNS topics..."
topics=$(aws sns list-topics --region "$AWS_REGION" --query 'Topics[].TopicArn' --output text | tr '\t' '\n')

for topic_arn in $topics; do
  tname=$(tf_id "$topic_arn")

  echo "=== Topic: $topic_arn ==="

  attrs=$(aws sns get-topic-attributes --topic-arn "$topic_arn" --region "$AWS_REGION")
  display_name=$(jq -r '.Attributes.DisplayName // empty' <<<"$attrs")

  cat >> "$MAIN" <<EOF
resource "aws_sns_topic" "${tname}" {
  name = "${display_name:-$tname}"
}
EOF

  ( cd "$TF_DIR" && safe_import "aws_sns_topic.${tname}" "$topic_arn" )

  # ---- Subscriptions ----
  echo "  ⏳ Listing subscriptions..."
  subs=$(aws sns list-subscriptions-by-topic --topic-arn "$topic_arn" --region "$AWS_REGION" \
    --query 'Subscriptions[].SubscriptionArn' --output text | tr '\t' '\n')

  for sub_arn in $subs; do
    [[ "$sub_arn" == "PendingConfirmation" ]] && continue
    sname=$(tf_id "$sub_arn")

    sub=$(aws sns get-subscription-attributes --subscription-arn "$sub_arn" --region "$AWS_REGION")
    protocol=$(jq -r '.Attributes.Protocol' <<<"$sub")
    endpoint=$(jq -r '.Attributes.Endpoint' <<<"$sub")

    cat >> "$MAIN" <<EOF
resource "aws_sns_topic_subscription" "${sname}" {
  topic_arn = aws_sns_topic.${tname}.arn
  protocol  = "${protocol}"
  endpoint  = "${endpoint}"
}
EOF

    ( cd "$TF_DIR" && safe_import "aws_sns_topic_subscription.${sname}" "$sub_arn" )
  done
done

terraform fmt -recursive "$TF_DIR" >/dev/null || true
echo "✅ Done. Topics + Subscriptions imported into $MAIN"
