########################################################
# Generated by import_sns.sh
########################################################

resource "aws_sns_topic" "arn_aws_sns_us_east_1_204469479814_Default_CloudWatch_Alarms_Topic" {
  name = "arn_aws_sns_us_east_1_204469479814_Default_CloudWatch_Alarms_Topic"
}
resource "aws_sns_topic_subscription" "arn_aws_sns_us_east_1_204469479814_Default_CloudWatch_Alarms_Topic_d2eefb8e_3400_4cab_8275_2f44756fdedd" {
  topic_arn = aws_sns_topic.arn_aws_sns_us_east_1_204469479814_Default_CloudWatch_Alarms_Topic.arn
  protocol  = "email"
  endpoint  = "cmonthe8@outlook.com"
}

